Pedi para o chat gpt cria alguns desafios para eu estuda Numpy.

# Desafio 1: Operações Básicas com Arrays
> Crie dois arrays NumPy de 1D com 10 elementos aleatórios inteiros entre 1 e 100. Em seguida, realize as seguintes operações:

- Some os dois arrays.
- Multiplique os dois arrays.
- Encontre o valor máximo e mínimo de cada array.
- Calcule a média e a variância de cada array.

In [2]:
import numpy as np


In [3]:
# Desafio 1

array1 = np.array([0, 5, 6, 7, 10, 3, 1, 2, 4, 5])
array2 = np.array([5, 3, 7, 2, 11, 3, 2, 3, 4, 10])

soma = array1 + array2
multiplicacao = array1 * array2
maximo = np.array([array1.max(), array2.max()])
media = np.array([array1.mean(), array2.mean()])
variancia = np.array([array1.var(), array2.var()])

print(soma)
print(multiplicacao)
print(maximo)
print(media)
print(variancia)

[ 5  8 13  9 21  6  3  5  8 15]
[  0  15  42  14 110   9   2   6  16  50]
[10 11]
[4.3 5. ]
[8.01 9.6 ]


# Desafio 2: Indexação e Slicing
> Dado um array NumPy 2D de 5x5 criado com números inteiros de 1 a 25, resolva:

- Extraia a segunda linha do array.
- Extraia a terceira coluna do array.
- Extraia o subarray 3x3 do centro do array.
- Substitua os valores da primeira coluna por zero.

In [4]:
# Desafio 2

# gerar dados aleatórios
from numpy.random import default_rng
rng=default_rng()
a = rng.integers(25, size= (5,5))

# Definição das variaveis 
segunda_linha = a[1]
terceira_coluna = a[:, 2]

#substitui os valores da primeira coluna por zero
a[:, 0] = 0

# Extração do subarray 3x3 do centro
subarray_centro = a[1:4, 1:4]

print(segunda_linha)
print(terceira_coluna)
print(a)
print(subarray_centro)





[ 0  0  2 20 21]
[ 9  2 20 11 24]
[[ 0 20  9  5 16]
 [ 0  0  2 20 21]
 [ 0 18 20 24 19]
 [ 0 16 11 22  6]
 [ 0 18 24 14  5]]
[[ 0  2 20]
 [18 20 24]
 [16 11 22]]


# Desafio 3: Transformações e Redimensionamento
> Crie um array 1D com 12 elementos inteiros aleatórios entre 1 e 50. Em seguida:

- Redimensione esse array para uma matriz 3x4.
- Transponha essa matriz.
- Aplique a função sqrt do NumPy em todos os elementos.
- Concatene essa matriz com uma nova matriz 3x4 de números aleatórios.

In [5]:
# criando um array aletório
a = rng.integers(50, size=(12))

# redimensionando 

array_redimensionado = np.resize(a, (3,4))

print(f'Array original: {a}')
print(f'Array redimensionado:\n {array_redimensionado}')

Array original: [10  9 43 23 10 28  4  3 21 10 40 11]
Array redimensionado:
 [[10  9 43 23]
 [10 28  4  3]
 [21 10 40 11]]


# Desafio 4: Estatísticas e Agregações
> Crie um array 2D de 100x10 onde cada elemento seja um número aleatório seguindo uma distribuição normal com média 50 e desvio padrão 10. Agora:

- Calcule a média de cada coluna.
- Encontre o índice do valor máximo de cada linha.
- Filtre o array para obter apenas os valores maiores que 60.
- Conte quantos valores são menores que 40.

In [37]:
# Definindo os parâmetros da distribuição normal
media = 50
desvio_padrao = 10

# Criando o array 2D com 100 linhas e 10 colunas
array_normal = np.random.normal(loc=media, scale=desvio_padrao, size=(100, 10))

# Suponha que 'array_normal' é o array 2D de 100x10 que criamos anteriormente
media_por_coluna = np.mean(array_normal, axis=0)

# Exibindo as médias de cada coluna
print('Média de cada coluna:', media_por_coluna)

valor_maximo_linha = np.max(array_normal, axis=1)
print('valor maximo de cada linha:', valor_maximo_linha)

maior_60 = array_normal[array_normal > 60]
print('valores maiores que 60:' , maior_60)

menores_40 = len(array_normal[array_normal < 40])

print(f'contagem dos valores menores que 40: {menores_40} valores')

Média de cada coluna: [50.92679589 49.56763925 52.1588961  49.31953865 48.50814009 51.5120877
 51.26942153 50.19905185 50.71683754 49.41637539]
valor maximo de cada linha: [63.46161197 53.88454565 68.11168676 59.34110501 64.53706916 62.18012768
 63.84747441 75.28374909 74.31617293 68.31335169 64.6707681  67.53824
 56.29739317 64.7977097  65.36613725 66.56447842 54.45808167 69.77622131
 64.1275059  67.43863198 67.96208078 69.0457448  60.2365967  68.43033652
 57.99901441 66.21610192 73.73188939 71.2165289  66.59025208 57.34945362
 58.87635621 75.94899769 55.92831254 69.07258198 60.65203737 62.39631354
 67.80810965 62.69202397 71.7178848  69.84515768 80.11658385 69.63299344
 67.83513111 67.27993615 66.34670357 69.73970175 62.51371007 60.4850881
 62.8543654  75.33462682 75.07963456 67.13341913 68.409394   64.70949869
 62.95003274 62.56981743 65.26312995 74.44431706 63.53483675 58.47976589
 64.75491941 59.94911074 55.80670944 70.70255034 68.25350656 69.97167959
 59.59525198 59.52269367 72.3