Pedi para o chat gpt cria alguns desafios para eu estuda Numpy.

# Desafio 1: Operações Básicas com Arrays
> Crie dois arrays NumPy de 1D com 10 elementos aleatórios inteiros entre 1 e 100. Em seguida, realize as seguintes operações:

- Some os dois arrays.
- Multiplique os dois arrays.
- Encontre o valor máximo e mínimo de cada array.
- Calcule a média e a variância de cada array.

In [15]:
import numpy as np


In [55]:
# Desafio 1

array1 = np.array([0, 5, 6, 7, 10, 3, 1, 2, 4, 5])
array2 = np.array([5, 3, 7, 2, 11, 3, 2, 3, 4, 10])

soma = array1 + array2
multiplicacao = array1 * array2
maximo = np.array([array1.max(), array2.max()])
media = np.array([array1.mean(), array2.mean()])
variancia = np.array([array1.var(), array2.var()])

print(soma)
print(multiplicacao)
print(maximo)
print(media)
print(variancia)

[ 5  8 13  9 21  6  3  5  8 15]
[  0  15  42  14 110   9   2   6  16  50]
[10 11]
[4.3 5. ]
[8.01 9.6 ]


# Desafio 2: Indexação e Slicing
> Dado um array NumPy 2D de 5x5 criado com números inteiros de 1 a 25, resolva:

- Extraia a segunda linha do array.
- Extraia a terceira coluna do array.
- Extraia o subarray 3x3 do centro do array.
- Substitua os valores da primeira coluna por zero.

In [104]:
# Desafio 2

# gerar dados aleatórios
from numpy.random import default_rng
rng=default_rng()
a = rng.integers(25, size= (5,5))

# Definição das variaveis 
segunda_linha = a[1]
terceira_coluna = a[:, 2]

#substitui os valores da primeira coluna por zero
a[:, 0] = 0

print(segunda_linha)
print(terceira_coluna)
print(a)





[ 0  2 16 18 18]
[ 4 16  5  6 19]
[[ 0  6  4 24 12]
 [ 0  2 16 18 18]
 [ 0 16  5 23 17]
 [ 0 17  6  4 20]
 [ 0 15 19  3  8]]
