Pedi para o chat gpt cria alguns desafios para eu estuda Numpy.

# Desafio 1: Operações Básicas com Arrays
> Crie dois arrays NumPy de 1D com 10 elementos aleatórios inteiros entre 1 e 100. Em seguida, realize as seguintes operações:

- Some os dois arrays.
- Multiplique os dois arrays.
- Encontre o valor máximo e mínimo de cada array.
- Calcule a média e a variância de cada array.

In [1]:
import numpy as np


In [2]:
# Desafio 1

array1 = np.array([0, 5, 6, 7, 10, 3, 1, 2, 4, 5])
array2 = np.array([5, 3, 7, 2, 11, 3, 2, 3, 4, 10])

soma = array1 + array2
multiplicacao = array1 * array2
maximo = np.array([array1.max(), array2.max()])
media = np.array([array1.mean(), array2.mean()])
variancia = np.array([array1.var(), array2.var()])

print(soma)
print(multiplicacao)
print(maximo)
print(media)
print(variancia)

[ 5  8 13  9 21  6  3  5  8 15]
[  0  15  42  14 110   9   2   6  16  50]
[10 11]
[4.3 5. ]
[8.01 9.6 ]


# Desafio 2: Indexação e Slicing
> Dado um array NumPy 2D de 5x5 criado com números inteiros de 1 a 25, resolva:

- Extraia a segunda linha do array.
- Extraia a terceira coluna do array.
- Extraia o subarray 3x3 do centro do array.
- Substitua os valores da primeira coluna por zero.

In [3]:
# Desafio 2

# gerar dados aleatórios
from numpy.random import default_rng
rng=default_rng()
a = rng.integers(25, size= (5,5))

# Definição das variaveis 
segunda_linha = a[1]
terceira_coluna = a[:, 2]

#substitui os valores da primeira coluna por zero
a[:, 0] = 0

# Extração do subarray 3x3 do centro
subarray_centro = a[1:4, 1:4]

print(segunda_linha)
print(terceira_coluna)
print(a)
print(subarray_centro)





[ 0  0 19  1 23]
[14 19 15 19 15]
[[ 0 10 14  2  7]
 [ 0  0 19  1 23]
 [ 0  1 15 24 11]
 [ 0 21 19 10 15]
 [ 0 16 15 19 21]]
[[ 0 19  1]
 [ 1 15 24]
 [21 19 10]]


# Desafio 3: Transformações e Redimensionamento
> Crie um array 1D com 12 elementos inteiros aleatórios entre 1 e 50. Em seguida:

- Redimensione esse array para uma matriz 3x4.
- Transponha essa matriz.
- Aplique a função sqrt do NumPy em todos os elementos.
- Concatene essa matriz com uma nova matriz 3x4 de números aleatórios.

In [4]:
# criando um array aletório
a = rng.integers(50, size=(12))

# redimensionando 

array_redimensionado = np.resize(a, (3,4))

print(f'Array original: {a}')
print(f'Array redimensionado:\n {array_redimensionado}')

Array original: [35 49  5 22 23 33 39  1 13 12 36  1]
Array redimensionado:
 [[35 49  5 22]
 [23 33 39  1]
 [13 12 36  1]]


# Desafio 4: Estatísticas e Agregações
> Crie um array 2D de 100x10 onde cada elemento seja um número aleatório seguindo uma distribuição normal com média 50 e desvio padrão 10. Agora:

- Calcule a média de cada coluna.
- Encontre o índice do valor máximo de cada linha.
- Filtre o array para obter apenas os valores maiores que 60.
- Conte quantos valores são menores que 40.

In [5]:
# Definindo os parâmetros da distribuição normal
media = 50
desvio_padrao = 10

# Criando o array 2D com 100 linhas e 10 colunas
array_normal = np.random.normal(loc=media, scale=desvio_padrao, size=(100, 10))

# Suponha que 'array_normal' é o array 2D de 100x10 que criamos anteriormente
media_por_coluna = np.mean(array_normal, axis=0)

# Exibindo as médias de cada coluna
print('Média de cada coluna:', media_por_coluna)

valor_maximo_linha = np.max(array_normal, axis=1)
print('valor maximo de cada linha:', valor_maximo_linha)

maior_60 = array_normal[array_normal > 60]
print('valores maiores que 60:' , maior_60)

menores_40 = len(array_normal[array_normal < 40])

print(f'contagem dos valores menores que 40: {menores_40} valores')

Média de cada coluna: [49.57673546 49.38488411 50.97021633 50.81795763 49.20991989 51.51823872
 49.36241651 48.76979168 50.39287807 49.35384716]
valor maximo de cada linha: [59.70055681 71.35445797 61.53500823 69.4678441  71.73304319 60.49796979
 68.11953988 75.50966456 65.22800087 73.04871336 70.22444251 67.07320951
 56.04512498 67.80376147 64.79056023 65.09048818 61.88673542 68.16025837
 75.7745429  66.28550014 64.33649805 68.1953129  58.45662806 66.5169057
 63.43741148 70.7362282  60.02101954 63.38315444 79.46432699 70.56104047
 76.76322743 67.05668478 73.35235607 65.80229985 60.5578264  62.65232591
 63.37552745 71.76506583 56.81831458 77.84634066 61.92719103 61.03018921
 61.2979946  61.80765571 56.93620478 64.0295338  62.11503154 70.69220654
 71.26123693 65.14894991 69.07313582 67.80867945 68.58583235 57.69735104
 62.29558384 62.50701444 62.39907758 62.3859399  64.06941216 68.48855837
 65.25445543 75.53546554 69.08148024 61.15668163 61.32180728 67.70300042
 68.30672718 69.75257426 

In [25]:
# gerar dados aleatórios
rng=default_rng()
a = rng.integers(25, size= (3,4))

print(f'dados: {a}\n ------------')

media = a.mean()
print(f'A média é: {media}\n ------------')

desvio = a - media
print(f'O desvio é: {desvio}\n ------------')

variancia = (desvio ** 2)
print(f' a variancia é :{variancia}\n ------------')

desvio_padrao = variancia.sum() / len(a)
print(f' O desvio padrão é:{desvio_padrao}')
print(np.std(a, ddof=1))

#corrigir

dados: [[ 9  1  6  3]
 [19 12  3  9]
 [18 12  3 24]]
 ------------
A média é: 9.916666666666666
 ------------
O desvio é: [[-0.91666667 -8.91666667 -3.91666667 -6.91666667]
 [ 9.08333333  2.08333333 -6.91666667 -0.91666667]
 [ 8.08333333  2.08333333 -6.91666667 14.08333333]]
 ------------
 a variancia é :[[  0.84027778  79.50694444  15.34027778  47.84027778]
 [ 82.50694444   4.34027778  47.84027778   0.84027778]
 [ 65.34027778   4.34027778  47.84027778 198.34027778]]
 ------------
 O desvio padrão é:198.30555555555554
7.354137157636736
