Pedi para o chat gpt cria alguns desafios para eu estuda Numpy.

# Desafio 1: Operações Básicas com Arrays
> Crie dois arrays NumPy de 1D com 10 elementos aleatórios inteiros entre 1 e 100. Em seguida, realize as seguintes operações:

- Some os dois arrays.
- Multiplique os dois arrays.
- Encontre o valor máximo e mínimo de cada array.
- Calcule a média e a variância de cada array.

In [1]:
import numpy as np


In [2]:
# Desafio 1

array1 = np.array([0, 5, 6, 7, 10, 3, 1, 2, 4, 5])
array2 = np.array([5, 3, 7, 2, 11, 3, 2, 3, 4, 10])

soma = array1 + array2
multiplicacao = array1 * array2
maximo = np.array([array1.max(), array2.max()])
media = np.array([array1.mean(), array2.mean()])
variancia = np.array([array1.var(), array2.var()])

print(soma)
print(multiplicacao)
print(maximo)
print(media)
print(variancia)

[ 5  8 13  9 21  6  3  5  8 15]
[  0  15  42  14 110   9   2   6  16  50]
[10 11]
[4.3 5. ]
[8.01 9.6 ]


# Desafio 2: Indexação e Slicing
> Dado um array NumPy 2D de 5x5 criado com números inteiros de 1 a 25, resolva:

- Extraia a segunda linha do array.
- Extraia a terceira coluna do array.
- Extraia o subarray 3x3 do centro do array.
- Substitua os valores da primeira coluna por zero.

In [3]:
# Desafio 2

# gerar dados aleatórios
from numpy.random import default_rng
rng=default_rng()
a = rng.integers(25, size= (5,5))

# Definição das variaveis 
segunda_linha = a[1]
terceira_coluna = a[:, 2]

#substitui os valores da primeira coluna por zero
a[:, 0] = 0

# Extração do subarray 3x3 do centro
subarray_centro = a[1:4, 1:4]

print(segunda_linha)
print(terceira_coluna)
print(a)
print(subarray_centro)





[ 0 10 24  8 14]
[16 24 17 15 23]
[[ 0  6 16  0  2]
 [ 0 10 24  8 14]
 [ 0 22 17 12 24]
 [ 0 18 15  5 11]
 [ 0  3 23  5 10]]
[[10 24  8]
 [22 17 12]
 [18 15  5]]


# Desafio 3: Transformações e Redimensionamento
> Crie um array 1D com 12 elementos inteiros aleatórios entre 1 e 50. Em seguida:

- Redimensione esse array para uma matriz 3x4.
- Transponha essa matriz.
- Aplique a função sqrt do NumPy em todos os elementos.
- Concatene essa matriz com uma nova matriz 3x4 de números aleatórios.

In [4]:
# criando um array aletório
a = rng.integers(50, size=(12))

# redimensionando 

array_redimensionado = np.resize(a, (3,4))

print(f'Array original: {a}')
print(f'Array redimensionado:\n {array_redimensionado}')

Array original: [27  5 27 23 31 14 42 29 34 44 36 48]
Array redimensionado:
 [[27  5 27 23]
 [31 14 42 29]
 [34 44 36 48]]


# Desafio 4: Estatísticas e Agregações
> Crie um array 2D de 100x10 onde cada elemento seja um número aleatório seguindo uma distribuição normal com média 50 e desvio padrão 10. Agora:

- Calcule a média de cada coluna.
- Encontre o índice do valor máximo de cada linha.
- Filtre o array para obter apenas os valores maiores que 60.
- Conte quantos valores são menores que 40.

In [5]:
# Definindo os parâmetros da distribuição normal
media = 50
desvio_padrao = 10

# Criando o array 2D com 100 linhas e 10 colunas
array_normal = np.random.normal(loc=media, scale=desvio_padrao, size=(100, 10))

# Suponha que 'array_normal' é o array 2D de 100x10 que criamos anteriormente
media_por_coluna = np.mean(array_normal, axis=0)

# Exibindo as médias de cada coluna
print('Média de cada coluna:', media_por_coluna)

valor_maximo_linha = np.max(array_normal, axis=1)
print('valor maximo de cada linha:', valor_maximo_linha)

maior_60 = array_normal[array_normal > 60]
print('valores maiores que 60:' , maior_60)

menores_40 = len(array_normal[array_normal < 40])

print(f'contagem dos valores menores que 40: {menores_40} valores')

Média de cada coluna: [49.66550026 48.49170953 52.08210358 50.71874668 49.82719326 49.78878971
 50.18162009 49.65741673 48.95120344 48.83295607]
valor maximo de cada linha: [58.8830303  60.65334273 57.08512445 62.0430681  61.83700074 63.97197401
 63.07354655 67.32899836 64.24100231 64.00828887 55.87878768 72.77107923
 64.69657593 63.95789619 65.10583646 64.59231502 66.11773395 60.81804222
 64.0455077  59.37956247 63.76707263 63.97491189 52.8537719  63.36277731
 60.61551933 57.06526826 59.40799124 61.14792867 69.80970929 56.04251785
 62.93751488 60.78994206 64.33814147 66.72298497 54.08751877 66.54572206
 61.88076708 60.87740817 65.80687803 66.61018601 61.72750748 64.08523443
 61.99575594 68.54797001 66.42072584 64.11866113 57.06947862 65.82584944
 59.7789405  59.85700493 63.61969941 59.65219552 59.2419455  62.71975369
 63.53871787 68.12812691 59.90016588 59.41326713 69.80360184 58.65239907
 63.74297648 58.12509244 76.97980307 60.90405462 57.71954881 67.98553367
 66.69610869 74.78812995

In [24]:
# gerar dados aleatórios

a = np.array([5, 6, 10, 20, 40, 50])

print(f'dados: {a}\n ------------')

# encontra a media dos dados
#media = a.mean()
media = a.sum() / len(a)
print(f'A média é: {media}\n ------------')

#Encontra o desvio
desvio = a - media
print(f'O desvio é: {desvio}\n ------------')

#Encontra a Variancia
variancia = (desvio ** 2) # eleva ao quadrado
print(f' a variancia é :{variancia} soma:{variancia.sum()}\n ------------')

#Econtra o desvio padrão populacional
desvio_padrao = variancia.sum() / len(a)
desvio_padrao = desvio_padrao ** 0.5 # tira a raiz quadrada do numero

print(f' O desvio padrão é:{desvio_padrao}\n ------------')
print(np.std(a, ddof=0))



dados: [ 5  6 10 20 40 50]
 ------------
A média é: 21.833333333333332
 ------------
O desvio é: [-16.83333333 -15.83333333 -11.83333333  -1.83333333  18.16666667
  28.16666667]
 ------------
 a variancia é :[283.36111111 250.69444444 140.02777778   3.36111111 330.02777778
 793.36111111] soma:1800.8333333333333
 ------------
 O desvio padrão é:17.324516988617283
 ------------
17.324516988617283


População vs. Amostra: O desvio padrão populacional é usado quando você tem todos os dados da população, enquanto o desvio padrão amostral é usado quando você tem apenas uma amostra.
Divisão por N ou N-1: No desvio padrão populacional, divide-se por  𝑁

N (tamanho da população), enquanto no desvio padrão amostral divide-se por  (𝑛 −1)

n−1 (tamanho da amostra menos um), para corrigir o viés.

Se você está trabalhando com uma amostra e deseja estimar o desvio padrão da população com base nessa amostra, deve usar o desvio padrão amostral. Se você tem dados de toda a população, usa o desvio padrão populacional.

In [30]:
# DESVIO PADRÃO AMOSTRAL

desvio_padrao_amostral = variancia.sum() / (len(a) -1)
desvio_padrao_amostral = desvio_padrao_amostral ** 0.5

print(desvio_padrao_amostral)
print(np.std(a, ddof=1))


18.978057505094313
18.978057505094313
